import Footer from "./components/Footer";
import NavBar from "./components/NavBar";
import "./globals.css";
import ConditionalBanner from "./components/ConditionalBanner";

export const metadata = {
  title: "Next.js CRUD App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const pathName = usePathname();

  return (
    <html lang="en">
      <body>
        <NavBar></NavBar>
       <ConditionalBanner/>
        <div className="container mx-auto p-4">{children}</div>
        <Footer></Footer>
      </body>
    </html>
  );
}
